apiVersion: v1
kind: Namespace
metadata:
  name: okd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: okd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: okd
---
apiVersion: v1
kind: Service
metadata:
  name: okd-console
  namespace: okd
spec:
  ports:
    - port: 9000
      nodePort: 30001
  selector:
    app: okd-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okd-deployment
  namespace: okd
spec:
  selector:
    matchLabels:
      app: okd-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: okd-app
    spec:
      serviceAccountName: admin-user
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/jibutech/okd:latest
          imagePullPolicy: Always
          name: console
          ports:
            - containerPort: 9000
              name: console-port

